// Code generated by qtc from "home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/ui/pages/home.qtpl:1
package pages

//line internal/ui/pages/home.qtpl:3
import "time"

//line internal/ui/pages/home.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/ui/pages/home.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/ui/pages/home.qtpl:6
type Product struct {
	ID          int
	Title       string
	Description string
	Price       float64
	ImageUrl    string
	InStock     bool
}

type HomePageData struct {
	SiteName   string
	UserName   string
	Products   []Product
	TotalItems int
	IsLoggedIn bool
}

//line internal/ui/pages/home.qtpl:25
func StreamHeader(qw422016 *qt422016.Writer, siteName string, isLoggedIn bool, userName string) {
//line internal/ui/pages/home.qtpl:25
	qw422016.N().S(`
<header class="header">
    <nav class="navbar">
        <div class="logo">
            <h1>`)
//line internal/ui/pages/home.qtpl:29
	qw422016.E().S(siteName)
//line internal/ui/pages/home.qtpl:29
	qw422016.N().S(`</h1>
        </div>
        <ul class="nav-menu">
            <li><a href="/">Inicio</a></li>
            <li><a href="/productos">Productos</a></li>
            <li><a href="/about">Acerca</a></li>
            <li><a href="/contact">Contacto</a></li>
        </ul>
        <div class="user-section">
            `)
//line internal/ui/pages/home.qtpl:38
	if isLoggedIn {
//line internal/ui/pages/home.qtpl:38
		qw422016.N().S(`
                <span class="welcome">Hola, `)
//line internal/ui/pages/home.qtpl:39
		qw422016.E().S(userName)
//line internal/ui/pages/home.qtpl:39
		qw422016.N().S(`!</span>
                <a href="/logout" class="btn-logout">Salir</a>
            `)
//line internal/ui/pages/home.qtpl:41
	} else {
//line internal/ui/pages/home.qtpl:41
		qw422016.N().S(`
                <a href="/login" class="btn-login">Iniciar Sesión</a>
            `)
//line internal/ui/pages/home.qtpl:43
	}
//line internal/ui/pages/home.qtpl:43
	qw422016.N().S(`
        </div>
    </nav>
</header>
`)
//line internal/ui/pages/home.qtpl:47
}

//line internal/ui/pages/home.qtpl:47
func WriteHeader(qq422016 qtio422016.Writer, siteName string, isLoggedIn bool, userName string) {
//line internal/ui/pages/home.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:47
	StreamHeader(qw422016, siteName, isLoggedIn, userName)
//line internal/ui/pages/home.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:47
}

//line internal/ui/pages/home.qtpl:47
func Header(siteName string, isLoggedIn bool, userName string) string {
//line internal/ui/pages/home.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:47
	WriteHeader(qb422016, siteName, isLoggedIn, userName)
//line internal/ui/pages/home.qtpl:47
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:47
	return qs422016
//line internal/ui/pages/home.qtpl:47
}

//line internal/ui/pages/home.qtpl:50
func StreamHero(qw422016 *qt422016.Writer, title, subtitle string) {
//line internal/ui/pages/home.qtpl:50
	qw422016.N().S(`
<section class="hero">
    <div class="hero-content">
        <h1 class="hero-title">`)
//line internal/ui/pages/home.qtpl:53
	qw422016.E().S(title)
//line internal/ui/pages/home.qtpl:53
	qw422016.N().S(`</h1>
        <p class="hero-subtitle">`)
//line internal/ui/pages/home.qtpl:54
	qw422016.E().S(subtitle)
//line internal/ui/pages/home.qtpl:54
	qw422016.N().S(`</p>
        <div class="hero-actions">
            <a href="/productos" class="btn btn-primary">Ver Productos</a>
            <a href="/about" class="btn btn-secondary">Conocer Más</a>
        </div>
    </div>
</section>
`)
//line internal/ui/pages/home.qtpl:61
}

//line internal/ui/pages/home.qtpl:61
func WriteHero(qq422016 qtio422016.Writer, title, subtitle string) {
//line internal/ui/pages/home.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:61
	StreamHero(qw422016, title, subtitle)
//line internal/ui/pages/home.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:61
}

//line internal/ui/pages/home.qtpl:61
func Hero(title, subtitle string) string {
//line internal/ui/pages/home.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:61
	WriteHero(qb422016, title, subtitle)
//line internal/ui/pages/home.qtpl:61
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:61
	return qs422016
//line internal/ui/pages/home.qtpl:61
}

//line internal/ui/pages/home.qtpl:64
func StreamProductCard(qw422016 *qt422016.Writer, product Product) {
//line internal/ui/pages/home.qtpl:64
	qw422016.N().S(`
<div class="product-card">
    <div class="product-image">
        <img src="`)
//line internal/ui/pages/home.qtpl:67
	qw422016.E().S(product.ImageUrl)
//line internal/ui/pages/home.qtpl:67
	qw422016.N().S(`" alt="`)
//line internal/ui/pages/home.qtpl:67
	qw422016.E().S(product.Title)
//line internal/ui/pages/home.qtpl:67
	qw422016.N().S(`">
        `)
//line internal/ui/pages/home.qtpl:68
	if !product.InStock {
//line internal/ui/pages/home.qtpl:68
		qw422016.N().S(`
            <span class="badge badge-out">Agotado</span>
        `)
//line internal/ui/pages/home.qtpl:70
	}
//line internal/ui/pages/home.qtpl:70
	qw422016.N().S(`
    </div>
    <div class="product-info">
        <h3 class="product-title">`)
//line internal/ui/pages/home.qtpl:73
	qw422016.E().S(product.Title)
//line internal/ui/pages/home.qtpl:73
	qw422016.N().S(`</h3>
        <p class="product-description">`)
//line internal/ui/pages/home.qtpl:74
	qw422016.E().S(product.Description)
//line internal/ui/pages/home.qtpl:74
	qw422016.N().S(`</p>
        <div class="product-footer">
            <span class="product-price">
                $`)
//line internal/ui/pages/home.qtpl:77
	qw422016.N().F(product.Price)
//line internal/ui/pages/home.qtpl:77
	qw422016.N().S(`
            </span>
            `)
//line internal/ui/pages/home.qtpl:79
	if product.InStock {
//line internal/ui/pages/home.qtpl:79
		qw422016.N().S(`
                <button class="btn btn-add-cart" data-id="`)
//line internal/ui/pages/home.qtpl:80
		qw422016.N().D(product.ID)
//line internal/ui/pages/home.qtpl:80
		qw422016.N().S(`">
                    Agregar al Carrito
                </button>
            `)
//line internal/ui/pages/home.qtpl:83
	} else {
//line internal/ui/pages/home.qtpl:83
		qw422016.N().S(`
                <button class="btn btn-disabled" disabled>
                    No Disponible
                </button>
            `)
//line internal/ui/pages/home.qtpl:87
	}
//line internal/ui/pages/home.qtpl:87
	qw422016.N().S(`
        </div>
    </div>
</div>
`)
//line internal/ui/pages/home.qtpl:91
}

//line internal/ui/pages/home.qtpl:91
func WriteProductCard(qq422016 qtio422016.Writer, product Product) {
//line internal/ui/pages/home.qtpl:91
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:91
	StreamProductCard(qw422016, product)
//line internal/ui/pages/home.qtpl:91
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:91
}

//line internal/ui/pages/home.qtpl:91
func ProductCard(product Product) string {
//line internal/ui/pages/home.qtpl:91
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:91
	WriteProductCard(qb422016, product)
//line internal/ui/pages/home.qtpl:91
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:91
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:91
	return qs422016
//line internal/ui/pages/home.qtpl:91
}

//line internal/ui/pages/home.qtpl:94
func StreamProductGrid(qw422016 *qt422016.Writer, products []Product) {
//line internal/ui/pages/home.qtpl:94
	qw422016.N().S(`
<section class="products-section">
    <div class="container">
        <h2 class="section-title">Nuestros Productos</h2>
        <div class="product-grid">
            `)
//line internal/ui/pages/home.qtpl:99
	if len(products) > 0 {
//line internal/ui/pages/home.qtpl:99
		qw422016.N().S(`
                `)
//line internal/ui/pages/home.qtpl:100
		for _, product := range products {
//line internal/ui/pages/home.qtpl:100
			qw422016.N().S(`
                    `)
//line internal/ui/pages/home.qtpl:101
			StreamProductCard(qw422016, product)
//line internal/ui/pages/home.qtpl:101
			qw422016.N().S(`
                `)
//line internal/ui/pages/home.qtpl:102
		}
//line internal/ui/pages/home.qtpl:102
		qw422016.N().S(`
            `)
//line internal/ui/pages/home.qtpl:103
	} else {
//line internal/ui/pages/home.qtpl:103
		qw422016.N().S(`
                <div class="empty-state">
                    <p>No hay productos disponibles en este momento.</p>
                </div>
            `)
//line internal/ui/pages/home.qtpl:107
	}
//line internal/ui/pages/home.qtpl:107
	qw422016.N().S(`
        </div>
    </div>
</section>
`)
//line internal/ui/pages/home.qtpl:111
}

//line internal/ui/pages/home.qtpl:111
func WriteProductGrid(qq422016 qtio422016.Writer, products []Product) {
//line internal/ui/pages/home.qtpl:111
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:111
	StreamProductGrid(qw422016, products)
//line internal/ui/pages/home.qtpl:111
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:111
}

//line internal/ui/pages/home.qtpl:111
func ProductGrid(products []Product) string {
//line internal/ui/pages/home.qtpl:111
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:111
	WriteProductGrid(qb422016, products)
//line internal/ui/pages/home.qtpl:111
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:111
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:111
	return qs422016
//line internal/ui/pages/home.qtpl:111
}

//line internal/ui/pages/home.qtpl:114
func StreamStats(qw422016 *qt422016.Writer, totalProducts, inStock, categories int) {
//line internal/ui/pages/home.qtpl:114
	qw422016.N().S(`
<section class="stats">
    <div class="container">
        <div class="stats-grid">
            <div class="stat-item">
                <div class="stat-number">`)
//line internal/ui/pages/home.qtpl:119
	qw422016.N().D(totalProducts)
//line internal/ui/pages/home.qtpl:119
	qw422016.N().S(`+</div>
                <div class="stat-label">Productos</div>
            </div>
            <div class="stat-item">
                <div class="stat-number">`)
//line internal/ui/pages/home.qtpl:123
	qw422016.N().D(inStock)
//line internal/ui/pages/home.qtpl:123
	qw422016.N().S(`</div>
                <div class="stat-label">En Stock</div>
            </div>
            <div class="stat-item">
                <div class="stat-number">`)
//line internal/ui/pages/home.qtpl:127
	qw422016.N().D(categories)
//line internal/ui/pages/home.qtpl:127
	qw422016.N().S(`</div>
                <div class="stat-label">Categorías</div>
            </div>
        </div>
    </div>
</section>
`)
//line internal/ui/pages/home.qtpl:133
}

//line internal/ui/pages/home.qtpl:133
func WriteStats(qq422016 qtio422016.Writer, totalProducts, inStock, categories int) {
//line internal/ui/pages/home.qtpl:133
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:133
	StreamStats(qw422016, totalProducts, inStock, categories)
//line internal/ui/pages/home.qtpl:133
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:133
}

//line internal/ui/pages/home.qtpl:133
func Stats(totalProducts, inStock, categories int) string {
//line internal/ui/pages/home.qtpl:133
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:133
	WriteStats(qb422016, totalProducts, inStock, categories)
//line internal/ui/pages/home.qtpl:133
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:133
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:133
	return qs422016
//line internal/ui/pages/home.qtpl:133
}

//line internal/ui/pages/home.qtpl:136
func StreamFooter(qw422016 *qt422016.Writer) {
//line internal/ui/pages/home.qtpl:136
	qw422016.N().S(`
<footer class="footer">
    <div class="container">
        <div class="footer-content">
            <div class="footer-section">
                <h4>Sobre Nosotros</h4>
                <p>Tu tienda de confianza desde `)
//line internal/ui/pages/home.qtpl:142
	qw422016.N().D(time.Now().Year() - 5)
//line internal/ui/pages/home.qtpl:142
	qw422016.N().S(`.</p>
            </div>
            <div class="footer-section">
                <h4>Enlaces Rápidos</h4>
                <ul>
                    <li><a href="/terminos">Términos y Condiciones</a></li>
                    <li><a href="/privacidad">Política de Privacidad</a></li>
                    <li><a href="/envios">Envíos y Devoluciones</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h4>Síguenos</h4>
                <div class="social-links">
                    <a href="#" aria-label="Facebook">Facebook</a>
                    <a href="#" aria-label="Twitter">Twitter</a>
                    <a href="#" aria-label="Instagram">Instagram</a>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; `)
//line internal/ui/pages/home.qtpl:162
	qw422016.N().D(time.Now().Year())
//line internal/ui/pages/home.qtpl:162
	qw422016.N().S(` Mi Tienda. Todos los derechos reservados.</p>
        </div>
    </div>
</footer>
`)
//line internal/ui/pages/home.qtpl:166
}

//line internal/ui/pages/home.qtpl:166
func WriteFooter(qq422016 qtio422016.Writer) {
//line internal/ui/pages/home.qtpl:166
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:166
	StreamFooter(qw422016)
//line internal/ui/pages/home.qtpl:166
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:166
}

//line internal/ui/pages/home.qtpl:166
func Footer() string {
//line internal/ui/pages/home.qtpl:166
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:166
	WriteFooter(qb422016)
//line internal/ui/pages/home.qtpl:166
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:166
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:166
	return qs422016
//line internal/ui/pages/home.qtpl:166
}

//line internal/ui/pages/home.qtpl:169
func StreamHomePage(qw422016 *qt422016.Writer, data HomePageData) {
//line internal/ui/pages/home.qtpl:169
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Tienda online con los mejores productos">
    <title>`)
//line internal/ui/pages/home.qtpl:176
	qw422016.E().S(data.SiteName)
//line internal/ui/pages/home.qtpl:176
	qw422016.N().S(` - Inicio</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }
        
        /* Header */
        .header {
            background: #2c3e50;
            color: white;
            padding: 1rem 0;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        
        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }
        
        .logo h1 {
            font-size: 1.5rem;
        }
        
        .nav-menu {
            display: flex;
            list-style: none;
            gap: 2rem;
        }
        
        .nav-menu a {
            color: white;
            text-decoration: none;
            transition: opacity 0.3s;
        }
        
        .nav-menu a:hover {
            opacity: 0.8;
        }
        
        .user-section {
            display: flex;
            align-items: center;
            gap: 1rem;
        }
        
        .welcome {
            font-weight: 500;
        }
        
        .btn-login, .btn-logout {
            padding: 0.5rem 1rem;
            background: #3498db;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            transition: background 0.3s;
        }
        
        .btn-logout {
            background: #e74c3c;
        }
        
        .btn-login:hover {
            background: #2980b9;
        }
        
        .btn-logout:hover {
            background: #c0392b;
        }
        
        /* Hero */
        .hero {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 5rem 2rem;
            text-align: center;
        }
        
        .hero-title {
            font-size: 3rem;
            margin-bottom: 1rem;
            animation: fadeInUp 0.8s ease-out;
        }
        
        .hero-subtitle {
            font-size: 1.3rem;
            margin-bottom: 2rem;
            opacity: 0.9;
            animation: fadeInUp 0.8s ease-out 0.2s backwards;
        }
        
        .hero-actions {
            display: flex;
            gap: 1rem;
            justify-content: center;
            animation: fadeInUp 0.8s ease-out 0.4s backwards;
        }
        
        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        /* Buttons */
        .btn {
            padding: 0.75rem 1.5rem;
            border-radius: 6px;
            text-decoration: none;
            font-weight: 600;
            transition: all 0.3s;
            display: inline-block;
            border: none;
            cursor: pointer;
        }
        
        .btn-primary {
            background: white;
            color: #667eea;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(0,0,0,0.2);
        }
        
        .btn-secondary {
            background: transparent;
            color: white;
            border: 2px solid white;
        }
        
        .btn-secondary:hover {
            background: white;
            color: #667eea;
        }
        
        /* Stats */
        .stats {
            padding: 3rem 0;
            background: #f8f9fa;
        }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 2rem;
            text-align: center;
        }
        
        .stat-number {
            font-size: 2.5rem;
            font-weight: bold;
            color: #667eea;
            margin-bottom: 0.5rem;
        }
        
        .stat-label {
            font-size: 1rem;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        /* Products */
        .products-section {
            padding: 4rem 0;
        }
        
        .section-title {
            text-align: center;
            font-size: 2.5rem;
            margin-bottom: 3rem;
            color: #2c3e50;
        }
        
        .product-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            gap: 2rem;
        }
        
        .product-card {
            background: white;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            transition: transform 0.3s, box-shadow 0.3s;
        }
        
        .product-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 5px 20px rgba(0,0,0,0.15);
        }
        
        .product-image {
            position: relative;
            width: 100%;
            height: 250px;
            overflow: hidden;
        }
        
        .product-image img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        
        .badge {
            position: absolute;
            top: 10px;
            right: 10px;
            padding: 0.3rem 0.6rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: bold;
            text-transform: uppercase;
        }
        
        .badge-out {
            background: #e74c3c;
            color: white;
        }
        
        .product-info {
            padding: 1.5rem;
        }
        
        .product-title {
            font-size: 1.25rem;
            margin-bottom: 0.5rem;
            color: #2c3e50;
        }
        
        .product-description {
            color: #666;
            margin-bottom: 1rem;
            font-size: 0.9rem;
            line-height: 1.4;
        }
        
        .product-footer {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 1rem;
        }
        
        .product-price {
            font-size: 1.5rem;
            font-weight: bold;
            color: #27ae60;
        }
        
        .btn-add-cart {
            background: #667eea;
            color: white;
            font-size: 0.9rem;
            padding: 0.5rem 1rem;
        }
        
        .btn-add-cart:hover {
            background: #5568d3;
        }
        
        .btn-disabled {
            background: #95a5a6;
            color: white;
            cursor: not-allowed;
            opacity: 0.6;
        }
        
        .empty-state {
            grid-column: 1 / -1;
            text-align: center;
            padding: 3rem;
            color: #666;
        }
        
        /* Footer */
        .footer {
            background: #2c3e50;
            color: white;
            padding: 3rem 0 1rem;
            margin-top: 4rem;
        }
        
        .footer-content {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 2rem;
            margin-bottom: 2rem;
        }
        
        .footer-section h4 {
            margin-bottom: 1rem;
            color: #3498db;
        }
        
        .footer-section ul {
            list-style: none;
        }
        
        .footer-section a {
            color: #bdc3c7;
            text-decoration: none;
            transition: color 0.3s;
        }
        
        .footer-section a:hover {
            color: white;
        }
        
        .social-links {
            display: flex;
            gap: 1rem;
        }
        
        .footer-bottom {
            text-align: center;
            padding-top: 2rem;
            border-top: 1px solid #34495e;
            color: #95a5a6;
        }
        
        /* Responsive */
        @media (max-width: 768px) {
            .navbar {
                flex-direction: column;
                gap: 1rem;
            }
            
            .hero-title {
                font-size: 2rem;
            }
            
            .hero-actions {
                flex-direction: column;
            }
            
            .product-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
    `)
//line internal/ui/pages/home.qtpl:546
	StreamHeader(qw422016, data.SiteName, data.IsLoggedIn, data.UserName)
//line internal/ui/pages/home.qtpl:546
	qw422016.N().S(`
    
    `)
//line internal/ui/pages/home.qtpl:548
	StreamHero(qw422016, "Bienvenido a "+data.SiteName, "Descubre los mejores productos al mejor precio")
//line internal/ui/pages/home.qtpl:548
	qw422016.N().S(`
    
    `)
//line internal/ui/pages/home.qtpl:550
	StreamStats(qw422016, data.TotalItems, len(data.Products), 12)
//line internal/ui/pages/home.qtpl:550
	qw422016.N().S(`
    
    `)
//line internal/ui/pages/home.qtpl:552
	StreamProductGrid(qw422016, data.Products)
//line internal/ui/pages/home.qtpl:552
	qw422016.N().S(`
    
    `)
//line internal/ui/pages/home.qtpl:554
	StreamFooter(qw422016)
//line internal/ui/pages/home.qtpl:554
	qw422016.N().S(`
    
    <script>
        // Event listeners para botones
        document.querySelectorAll('.btn-add-cart').forEach(btn => {
            btn.addEventListener('click', function() {
                const productId = this.dataset.id;
                alert('Producto ' + productId + ' agregado al carrito!');
            });
        });
    </script>
</body>
</html>
`)
//line internal/ui/pages/home.qtpl:567
}

//line internal/ui/pages/home.qtpl:567
func WriteHomePage(qq422016 qtio422016.Writer, data HomePageData) {
//line internal/ui/pages/home.qtpl:567
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/ui/pages/home.qtpl:567
	StreamHomePage(qw422016, data)
//line internal/ui/pages/home.qtpl:567
	qt422016.ReleaseWriter(qw422016)
//line internal/ui/pages/home.qtpl:567
}

//line internal/ui/pages/home.qtpl:567
func HomePage(data HomePageData) string {
//line internal/ui/pages/home.qtpl:567
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/ui/pages/home.qtpl:567
	WriteHomePage(qb422016, data)
//line internal/ui/pages/home.qtpl:567
	qs422016 := string(qb422016.B)
//line internal/ui/pages/home.qtpl:567
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/ui/pages/home.qtpl:567
	return qs422016
//line internal/ui/pages/home.qtpl:567
}
